version: '3.0'

services:
  dockerapi:
    image: dockerapi:latest
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      ConnectionStrings__OneByteDatabase: host=postgres;port=5432;database=${POSTGRES_DB};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
      ElasticSearch__Url: ${ELASTICSEARCH_URL:?err}
      Jwt__Key: ${JWT_KEY:?err}
      Jwt__Audience: ${JWT_AUDIENCE:?err}
      Jwt__Issuer: ${JWT_ISSUER:?err}
    networks:
      - onebyte
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:?err} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
    networks:
      - onebyte
networks:
  onebyte:
    driver: bridge
volumes:
  db_volume: